### PR TITLE
Add support for audit-policy logging

### PR DESCRIPTION
**Pull request by hh**

### CODE REVIEW

**Comment by ivan4th** [comment]
Thanks for the PR, sorry for delayed response.
There are a couple of problems overall...
1. Please run `build/genfixed.sh` to update the 'fixed' scripts (CircleCI fails because of this)
2. The change is not compatible with k8s 1.8 and 1.9.

E.g. for k8s 1.9 you get (see Travis job):
```
feature-gates: Invalid value: map[string]bool{"Auditing":true, "CoreDNS":false}: Auditing is not a valid feature name. Valid features are: [CoreDNS DynamicKubeletConfig SelfHosting StoreCertsInSecrets HighAvailability]
```
You need to either verify kubeadm vesion prior to enabling the feature gate, or just don't enable it by default, adding a note to `README.md`.

**Comment by RA489** [comment]
@hh please rebase.

**Comment by mogaika** [comment]
I signed it

**Comment by hh** [comment]
I just added audit log support for kind e2e.sh
Should I back port / rebate that here or have we moved to kind?

**Comment by mrbobbytables** [comment]
Closing as this project is being deprecated and retired in favor of [KinD](https://github.com/kubernetes-sigs/kind).

Please see this issue for more details:
https://github.com/kubernetes/org/issues/1016

/close

**Pull request closed without merging**
