### PR TITLE
set correct host value when running on linux

### PR DESCRIPTION
**Pull request by paulczar**
when running on linux with a local docker daemon the host should be set
to localhost and there is no need to add routes.

### CODE REVIEW

**Comment by stealthybox** [comment]
I also ran into this on minikube.
The cluster fails to setup CNI because `kubectl apply` is run from the host machine.
^ ( we should consider exec'ing into the dind to make this less error prone )

This is my local patch for this:  (adds KUBECTL_HOST and EXPOSE_ALL)
```diff
diff --git a/dind-cluster.sh b/dind-cluster.sh
index efaa87f..45bd03f 100755
--- a/dind-cluster.sh
+++ b/dind-cluster.sh
@@ -57,6 +57,10 @@ fi
 POD_NETWORK_CIDR="${POD_NETWORK_CIDR:-${DEFAULT_POD_NETWORK_CIDR}}"
 ETCD_HOST="${ETCD_HOST:-127.0.0.1}"
 GCE_HOSTED="${GCE_HOSTED:-false}"
+
+KUBECTL_HOST="${KUBECTL_HOST:-}"
+EXPOSE_ALL="${EXPOSE_ALL:-}"
+
 if [[ ${IP_MODE} = "ipv6" ]]; then
     DIND_SUBNET="${DIND_SUBNET:-fd00:10::}"
     dind_ip_base="${DIND_SUBNET}"
@@ -621,6 +625,9 @@ function dind::configure-kubectl {
       host="[::1]"
     fi
   fi
+  if [[ "${KUBECTL_HOST}" ]]; then
+      host="${KUBECTL_HOST}"
+  fi
   "${kubectl}" config set-cluster dind --server="http://${host}:${APISERVER_PORT}" --insecure-skip-tls-verify=true
   "${kubectl}" config set-context dind --cluster=dind
   "${kubectl}" config use-context dind
@@ -693,8 +700,14 @@ function dind::init {
   local -a opts
   dind::set-master-opts
   local local_host="127.0.0.1"
+  if [[ "${EXPOSE_ALL}" ]]; then
+    local_host="0.0.0.0"
+  fi
   if [[ ${IP_MODE} = "ipv6" ]]; then
-      local_host="[::1]"
+    local_host="[::1]"
+    if [[ "${EXPOSE_ALL}" ]]; then
+      local_host="[::]"
+    fi
   fi
   local container_id=$(dind::run kube-master "${kube_master_ip}" 1 ${local_host}:${APISERVER_PORT}:8080 ${master_opts[@]+"${master_opts[@]}"})
   # FIXME: I tried using custom tokens with 'kubeadm ex token create' but join failed with:
@@ -862,6 +875,9 @@ function dind::wait-for-ready {
   if [[ ${IP_MODE} = "ipv6" ]]; then
       local_host="[::1]"
   fi
+  if [[ "${KUBECTL_HOST}" ]]; then
+      local_host="${KUBECTL_HOST}"
+  fi
   dind::step "Access dashboard at:" "http://${local_host}:${APISERVER_PORT}/ui"
 }

@@ -966,8 +982,14 @@ function dind::restore {
       if [[ n -eq 0 ]]; then
         dind::step "Restoring master container"
         local local_host="127.0.0.1"
+        if [[ "${EXPOSE_ALL}" ]]; then
+          local_host="0.0.0.0"
+        fi
         if [[ ${IP_MODE} = "ipv6" ]]; then
           local_host="[::1]"
+          if [[ "${EXPOSE_ALL}" ]]; then
+            local_host="[::]"
+          fi
         fi
         dind::restore_container "$(dind::run -r kube-master "${kube_master_ip}" 1 ${local_host}:${APISERVER_PORT}:8080 ${master_opts[@]+"${master_opts[@]}"})"
         dind::step "Master container restored"
```

**Comment by ivan4th** [comment]
Thanks for the PR. Please modify the main script, `dind-cluster.sh`, then re-generate the `fixed/` scripts with `build/genfixed.sh`

**Comment by paulczar** [comment]
thanks for the pointer @ivan4th,  I've done that now.

**Comment by ivan4th** [comment]
Thanks!

**Pull request merged**
